### PR TITLE
Delegate to driver for header and status

### PR DESCRIPTION
**Pull request by mrloop**
See #82 , resolves header nil error

### CODE REVIEW

**Comment by jcoglan** [comment]
Thanks for the patch :)

**Comment by Intrepidd** [comment]
Thanks ! Any plan on cutting a new gem version with that ? Lost a bit of time on this issue

**Comment by jcoglan** [comment]
@Intrepidd Yes, as soon as I can get the [test suite](https://github.com/faye/wstest) run, which takes about a day.

**Comment by Intrepidd** [comment]
thanks ! :+1:

**Pull request merged**
